apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres_db_secret: ZG9ja2VydGVzdGRi
  postgres_user_secret: YWRtaW4=
  postgres_password_secret: c3VwZXJzZWNyZXRwYXNzd29yZA==