pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/natalliaseviaryn/devops-java-training.git'
            }
        }
        stage('Build') {
            steps {
                dir('books') {
                    sh './gradlew clean build'
                }
            }
        }
        stage('Test') {
            steps {
                dir('books') {
                    sh './gradlew test'
                }
            }
        }
        stage('Package') {
            steps {
                dir('books') {
                    sh './gradlew bootJar'
                }
            }
        }
    }

    post {
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}