services:
  helloworld:
    image: 'hello-world'
    deploy:
      replicas: 5
  books:
    image: 'natalliaseviaryn/books-app:latest'
    restart: always
    deploy:
      replicas: 1
    ports:
      - '8081:8080'
    env_file:
      - ./env/backend.env
    depends_on:
      db:
        condition: service_started
  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./env/postgres.env
    volumes:
      - pgdata141:/var/lib/postgresql/data
      - ./books/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata141:
