FROM gradle:8.10.2-jdk17 AS build

WORKDIR /app
COPY .. /app
RUN chmod +x gradlew
RUN ./gradlew build

FROM openjdk:17 AS runtime
WORKDIR /app
COPY --from=build /app/build/libs/books-0.1.0-SNAPSHOT.jar /app/books-0.1.0-SNAPSHOT.jar

ENV DEVOPS="Sergey Suhinin"

EXPOSE 8080

ENTRYPOINT ["java","-jar","books-0.1.0-SNAPSHOT.jar"]